"""add_approve

Revision ID: 8c88e60a419b
Revises: 01a750736ea0
Create Date: 2024-08-25 21:54:53.744729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c88e60a419b'
down_revision = '01a750736ea0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_bottle_bottle", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "approved",
                sa.Boolean(),
                nullable=False,
                server_default=sa.schema.DefaultClause("1")
            ),
            
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_bottle_bottle", schema=None) as batch_op:
        batch_op.drop_column("approved")
    # ### end Alembic commands ###
